import{a as u,i as a,S as R}from"./assets/vendor-DjDxajEQ.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api";const w="45109890-d15cee52eedc615dd4ac8bedf";async function h({q:r,page:n,per_page:i}){const l=new URLSearchParams({key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:i});try{const e=await u.get("?",{params:l});if(e.status!==200)throw new Error(`Server responded with status ${e.status}`);return console.log("API Response Data:",e.data),e.data}catch(e){throw e.response?(console.error("Server Response Error:",e.response.data),a.error({message:`Server error: ${e.response.status}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})):e.request?(console.error("No response received:",e.request),a.error({message:"No response from server",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})):(console.error("Error",e.message),a.error({message:`Error: ${e.message}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})),e}}const c={searchForm:document.querySelector(".js-form-container"),cardBox:document.querySelector(".card-container"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector('[data-action="load-more"]')};c.cardBox.addEventListener("click",r=>r.preventDefault());function m(){c.loader.style.display="inline-block"}function f(){c.loader.style.display="none"}let p=0;const x=10;function S(r){p<x&&(a.error({message:"Image failed to load.",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),p++),r.target.src="/fallback.jpg"}function b(r){const n=r.map(({webformatURL:e,largeImageURL:t,tags:d,likes:E,views:L,comments:v,downloads:C})=>`<li class="list-group-item scrol">
          <div class="search-card">
            <div class="card-img-box">
              <a class="card-link" href="${t}">
                <img class="card-img" src="${e}" alt="${d}">
              </a>
            </div>
            <div class="card-box-text">
              <p class="card-text">Likes<br><span>${E}</span></p>
              <p class="card-text">Views<br><span>${L}</span></p>
              <p class="card-text">Comments<br><span>${v}</span></p>
              <p class="card-text">Downloads<br><span>${C}</span></p>
            </div>
          </div>
        </li>`).join("");c.cardBox.insertAdjacentHTML("beforeend",n),c.cardBox.querySelectorAll(".card-img").forEach(e=>{e.addEventListener("error",S)}),new R(".card-container a",{captionsData:"alt",captionDelay:250,overlayOpacity:.9}).refresh()}class P{constructor(n,i){this.buttonEL=n,this.hiddenClass=i}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const o=new P(c.loadMoreBtn,"is-hidden");o.hide();const s={q:"",page:1,per_page:15,maxPage:0};function g(){navigator.onLine||(a.error({message:"No internet connection.",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o.hide())}window.addEventListener("online",g);window.addEventListener("offline",g);g();c.searchForm.addEventListener("submit",F);async function F(r){r.preventDefault(),c.cardBox.innerHTML="";const n=r.currentTarget;if(s.q=n.elements.search.value.toLowerCase().trim(),console.log("Form submitted"),console.log("Search term:",s.q),!s.q){a.error({message:"Please enter the data in the input field",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o.hide(),f();return}if(!navigator.onLine){a.error({message:"No internet connection.",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o.hide(),f();return}o.hide(),o.disable(),s.page=1;try{m();const{total:i,hits:l}=await h(s);if(console.log("API Response:",{total:i,hits:l}),s.maxPage=Math.ceil(i/s.per_page),!l.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o.hide(),f();return}b(l),s.page<s.maxPage?(o.show(),o.enable(),c.loadMoreBtn.addEventListener("click",y)):o.hide()}catch(i){o.hide(),a.error({message:`An error occurred: ${i.message}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})}finally{f(),n.reset()}}async function y(){if(!navigator.onLine){a.error({message:"No internet connection.",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),o.hide();return}o.disable();try{m(),s.page+=1;const{hits:r}=await h(s);if(console.log("Load More API Response:",r),!r.length){a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),o.hide(),c.loadMoreBtn.removeEventListener("click",y);return}b(r)}catch(r){o.hide(),a.error({message:`An error occurred: ${r.message}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})}finally{f(),s.page>=s.maxPage?(a.success({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),o.hide()):o.enable()}}
//# sourceMappingURL=index.js.map
