import{a as p,S as x,i as l}from"./assets/vendor-DjDxajEQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();p.defaults.baseURL="https://pixabay.com/api";const v="45109890-d15cee52eedc615dd4ac8bedf";async function h({q:r,page:o,per_page:i}){const n=new URLSearchParams({key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i});return await p.get("?",{params:n}).then(({data:e})=>e).catch(e=>console.log(e))}const c={searchForm:document.querySelector(".js-form-container"),cardBox:document.querySelector(".card-container"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),elem:document.querySelector(".scrol")};c.cardBox.addEventListener("click",r=>r.preventDefault());function m(){c.loader.style.display="inline-block"}function f(){c.loader.style.display="none"}function g(r){const o=r.map(({webformatURL:n,largeImageURL:e,tags:s,likes:d,views:y,comments:b,downloads:L})=>`<li class="list-group-item scrol"><div class="search-card">
   <div class="card-img-box">
     <a clas="card-link" href="${e}"><img class="card-img" src="${n}" alt="${s}"></a>
   </div>
   <div class="card-box-text">
     <p class="card-text">Likes<br><span>${d}</span></p>
     <p class="card-text">Views<br><span>${y}</span></p>
     <p class="card-text">Comments<br><span>${b}</span></p>
     <p class="card-text">Downloads<br><span>${L}</span></p>
   </div>
</div></li>`).join("");c.cardBox.insertAdjacentHTML("beforeend",o),new x(".card-container a",{captionsData:"alt",captionDelay:250,overlayOpacity:.9}).refresh()}class C{constructor(o,i){this.buttonEL=o,this.hiddenClass=i}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const a=new C(c.loadMoreBtn,"is-hidden");a.hide();const t={q:"",page:1,per_page:15,maxPage:0};c.searchForm.addEventListener("submit",E);async function E(r){r.preventDefault(),c.cardBox.innerHTML="";const o=r.currentTarget;if(t.q=o.elements.search.value.toLowerCase().trim(),!t.q){l.error({message:"Please enter the data in the input field",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),a.hide(),f();return}a.show(),a.disable(),t.page=1;try{m();const{total:i,hits:n}=await h(t);if(t.maxPage=Math.ceil(i/t.per_page),t.maxPage>1?(a.enable(),c.loadMoreBtn.addEventListener("click",u)):a.hide(),!n.length){a.disable(),l.error({message:"Sorry, there are no images matching<br>your search query. Please try again!",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"});return}if(!t.q){a.hide(),l.error({message:"Please enter the data in the input field",position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"});return}g(n)}catch(i){l.error({message:`${i.message}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"})}finally{f(),t.page===t.maxPage?(a.hide(),c.loadMoreBtn.removeEventListener("click",u)):a.enable(),o.reset()}}async function u(){a.disable(),t.page+=1;try{m();const{hits:r}=await h(t);g(r)}catch(r){l.error({message:`${r.message}`,position:"topRight",messageColor:"#ffffff",backgroundColor:"#EF4040"}),a.hide()}finally{f(),t.page===t.maxPage?(l.success({message:"We're sorry, but you've reached the end of search results",position:"topRight"}),a.hide()):a.enable()}}
//# sourceMappingURL=index.js.map
